---
dist: focal
sudo: required
before_install:
  - . /etc/os-release
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install buildah

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine DOTVER=3.12 DASHVER=3_12
  - OS=alpine DOTVER=3.13 DASHVER=3_13
  - OS=alpine DOTVER=edge DASHVER=edge
  - OS=archlinux DOTVER=latest DASHVER=latest
  - OS=centos DOTVER=7 DASHVER=7
  - OS=centos DOTVER=8 DASHVER=8
  - OS=debian DOTVER=bullseye DASHVER=bullseye
  - OS=debian DOTVER=buster DASHVER=buster
  - OS=debian DOTVER=stretch DASHVER=stretch
  - OS=fedora DOTVER=31 DASHVER=31
  - OS=fedora DOTVER=32 DASHVER=32
  - OS=ubi8 DOTVER=8.1 DASHVER=8_1
  - OS=ubi8 DOTVER=8.2 DASHVER=8_2
  - OS=ubuntu DOTVER=bionic DASHVER=bionic
  - OS=ubuntu DOTVER=focal DASHVER=focal
  - OS=ubuntu DOTVER=xenial DASHVER=xenial

before_script:
  - buildah login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PWD" docker.io
  - buildah login -u "$TARGET_REGISTRY_USER" -p "$TARGET_REGISTRY_PWD" quay.io

script:
  - ./build.sh $OS $DOTVER $DASHVER
  - buildah push quay.io/andrewrothstein/docker-python3:0.0.0-${OS}-${DOTVER}
