---
dist: focal
sudo: required
before_install:
  - . /etc/os-release
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install buildah

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine VER=3.12
  - OS=alpine VER=3.13
  - OS=alpine VER=edge
  - OS=archlinux VER=latest
  - OS=centos VER=7
  - OS=centos VER=8
  - OS=debian VER=bullseye
  - OS=debian VER=buster
  - OS=debian VER=stretch
  - OS=fedora VER=31
  - OS=fedora VER=32
  - OS=ubi8 VER=8.1
  - OS=ubi8 VER=8.2
  - OS=ubuntu VER=bionic
  - OS=ubuntu VER=focal
  - OS=ubuntu VER=xenial

before_script:
  - buildah login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PWD" docker.io
  - buildah login -u "$TARGET_REGISTRY_USER" -p "$TARGET_REGISTRY_PWD" quay.io

script:
  - ./build.sh $OS $VER
  - buildah push quay.io/andrewrothstein/docker-python3:0.0.0-${OS}-${VER}
