---
dist: focal
sudo: required
before_install:
  - sudo apt-get install -qq -y buildah

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine DOTVER=3.12 DASHVER=3_12
  - OS=alpine DOTVER=3.13 DASHVER=3_13
  - OS=alpine DOTVER=edge DASHVER=edge
  - OS=archlinux DOTVER=latest DASHVER=latest
  - OS=centos DOTVER=7 DASHVER=7
  - OS=centos DOTVER=8 DASHVER=8
  - OS=debian DOTVER=bullseye DASHVER=bullseye
  - OS=debian DOTVER=buster DASHVER=buster
  - OS=debian DOTVER=stretch DASHVER=stretch
  - OS=fedora DOTVER=31 DASHVER=31
  - OS=fedora DOTVER=32 DASHVER=32
  - OS=ubi8 DOTVER=8.1 DASHVER=8_1
  - OS=ubi8 DOTVER=8.2 DASHVER=8_2
  - OS=ubuntu DOTVER=bionic DASHVER=bionic
  - OS=ubuntu DOTVER=focal DASHVER=focal
  - OS=ubuntu DOTVER=xenial DASHVER=xenial

before_script:
  - buildah login -u "$TARGET_REGISTRY_USER" -p "$TARGET_REGISTRY_PWD" quay.io

script:
  - ./build.sh $OS $DOTVER $DASHVER
  - buildah push quay.io/andrewrothstein/docker-python3:${OS}_${DOTVER}
