---
name: dcb
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
env:
  TARGET_REGISTRY: ghcr.io
  TARGET_GROUPNAME: andrewrothstein
  TARGET_NAME: docker-python3
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - os: alpine
            ver: '3.13'
          - os: alpine
            ver: '3.14'
          - os: alpine
            ver: '3.15'
          - os: alpine
            ver: edge
          - os: archlinux
            ver: latest
          - os: centos
            ver: '8'
          - os: debian
            ver: bullseye
          - os: debian
            ver: buster
          - os: fedora
            ver: '34'
          - os: fedora
            ver: '35'
          - os: rockylinux
            ver: '8.4'
          - os: rockylinux
            ver: '8.5'
          - os: ubuntu
            ver: bionic
          - os: ubuntu
            ver: focal
    steps:
      - uses: actions/checkout@v2
      - run: sudo buildah login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}" docker.io
      - run: sudo buildah login -u "${{ github.actor }}" -p "${{ github.token }}" ghcr.io
      - run: |
          . container-build-lib
          buildah_build ${{ matrix.distro.os }} ${{ matrix.distro.ver }}
          buildah_push ${{ matrix.distro.os }} ${{ matrix.distro.ver }}
